// combat/engine.go — Pure turn-based combat logic, no rendering.
//
// THEORY — Separation of concerns:
// The combat engine is a pure state machine that takes actions as input and
// returns results as output. It knows nothing about sprites, screens, or pixels.
// This means we can test damage formulas, turn order, and flee mechanics with
// simple Go unit tests — no Ebitengine needed.
//
// THEORY — Turn order:
// Each round, we compare SPD stats to determine who acts first. If speeds are
// equal, the player gets priority (player-friendly design). This is simpler
// than Final Fantasy's ATB gauge but still rewards investing in SPD.
//
// THEORY — Damage formula:
// We use: base = ATK * multiplier - DEF / 2, then apply ±20% randomness.
// The DEF/2 means defense is strong but never makes you invincible.
// Floor at 1 ensures every hit does *something* — no zero-damage stalemates.
// This is close to Dragon Quest's formula, known for being easy to balance.
//
// THEORY — State machine:
// Combat flows: Start → PlayerTurn → (action resolves) → EnemyTurn → (action
// resolves) → check for victory/defeat → next round. The engine tracks this
// as a CombatPhase enum so the screen knows what to animate.
package combat

import (
	"math/rand"

	"cli_adventure/entity"
)

// Phase represents the current phase of combat.
type Phase int

const (
	PhaseStart      Phase = iota
	PhasePlayerTurn       // waiting for player to pick an action
	PhasePlayerAct        // player's action is resolving
	PhaseEnemyTurn        // enemy is about to act
	PhaseEnemyAct         // enemy's action is resolving
	PhaseVictory          // monster HP <= 0
	PhaseDefeat           // player HP <= 0
	PhaseFlee             // player successfully fled
	PhaseFleeFaild        // flee failed, enemy gets a free turn
)

// Action represents a combat action the player can take.
type Action int

const (
	ActionAttack Action = iota
	ActionMagic
	ActionDefend
	ActionFlee
	ActionItem  // use potion from bag
	ActionSkill // use a specific learned skill
)

// Result holds the outcome of a single action for the screen to animate.
type Result struct {
	Action         Action
	Damage         int
	IsCrit         bool
	Healed         int
	Message        string
	TargetIsPlayer bool // true if the player took damage
}

// Engine manages the state of a single combat encounter.
type Engine struct {
	Player  *entity.Player
	Monster *entity.Monster

	Phase   Phase
	Round   int
	Results []Result // results to animate this phase

	// State flags
	PlayerDefending bool
	EnemyGoesFirst  bool

	// Unified status effect system — replaces old ad-hoc flags
	// (ATKBuff, AegisActive, PoisonDmg, EnemyStunned, etc.)
	//
	// THEORY — Two separate slices:
	// PlayerEffects holds buffs ON the player (ATK Up, Regen, Aegis) and
	// debuffs FROM the enemy (Poison, ATK Down, Stun). EnemyEffects holds
	// debuffs ON the enemy (SPD Down, Burn) and buffs FROM the enemy's own
	// abilities (if enemies could buff themselves). The "on whom" determines
	// the slice, not "who applied it".
	PlayerEffects []StatusEffect
	EnemyEffects  []StatusEffect

	// Messages generated by effect ticks (DoT damage, buff expiry, etc.)
	// The combat screen reads these to display in sequence.
	EffectMessages []string

	// Boss special attack tracking
	bossAttackCounter int

	// Skill system: which skill the player selected (set before calling PlayerAction)
	SelectedSkillIdx int // index into player's learned skills

	// Item system: inventory index of the item the player wants to use
	SelectedItemIdx int // index into player.Items (set by combat screen before ActionItem)
}

// NewEngine creates a combat engine for a player vs monster encounter.
func NewEngine(player *entity.Player, monster *entity.Monster) *Engine {
	e := &Engine{
		Player:  player,
		Monster: monster,
		Phase:   PhaseStart,
		Round:   1,
	}
	// Determine initial turn order based on SPD (including gear bonuses)
	e.EnemyGoesFirst = monster.SPD > player.EffectiveSPD()
	return e
}

// Start transitions from PhaseStart to the first turn.
func (e *Engine) Start() {
	if e.EnemyGoesFirst {
		e.Phase = PhaseEnemyTurn
	} else {
		e.Phase = PhasePlayerTurn
	}
}

// PlayerAction processes the player's chosen action.
// Returns the result for animation. Transitions phase afterward.
func (e *Engine) PlayerAction(action Action) Result {
	e.Results = nil
	e.EffectMessages = nil
	var r Result

	// Tick player effects at start of player's turn (DoTs, buff expiry, regen)
	msgs := TickEffects(&e.PlayerEffects, &e.Player.Stats.HP, &e.Player.Stats.MaxHP)
	e.EffectMessages = append(e.EffectMessages, msgs...)

	// Check for stun: if player is stunned, skip their action
	if HasCondition(e.PlayerEffects, CondStun) {
		// Stun is consumed (1-turn stun = skip this turn)
		ConsumeCondition(&e.PlayerEffects, CondStun)
		r = Result{Action: action, Message: "You're stunned!"}
		e.Results = append(e.Results, r)
		e.Phase = PhasePlayerAct
		return r
	}

	// Check for blind: 50% miss chance on physical attacks
	if action == ActionAttack && HasCondition(e.PlayerEffects, CondBlind) {
		if rand.Intn(100) < 50 {
			r = Result{Action: ActionAttack, Message: "Attack missed!\n(Blinded)"}
			e.Results = append(e.Results, r)
			e.Phase = PhasePlayerAct
			return r
		}
	}

	switch action {
	case ActionAttack:
		r = e.calcPlayerAttack(1.0)
	case ActionMagic:
		r = e.calcPlayerMagic()
	case ActionSkill:
		r = e.calcUseSkill()
	case ActionDefend:
		r = e.calcPlayerDefend()
	case ActionFlee:
		r = e.calcFlee()
		if r.Action == ActionFlee {
			// Successful flee
			e.Phase = PhaseFlee
			e.Results = append(e.Results, r)
			return r
		}
		// Failed flee — enemy gets a free hit
		e.Phase = PhaseFleeFaild
		e.Results = append(e.Results, r)
		return r
	case ActionItem:
		r = e.calcUseItem()
	}

	e.Results = append(e.Results, r)
	e.Phase = PhasePlayerAct

	// Check if monster is dead
	if e.Monster.HP <= 0 {
		e.Monster.HP = 0
		e.Phase = PhaseVictory
	}

	return r
}

// EnemyAction processes the enemy's turn. Returns the result.
func (e *Engine) EnemyAction() Result {
	e.Results = nil
	e.EffectMessages = nil
	var r Result

	// Tick enemy effects at start of enemy's turn (DoTs on enemy, buff expiry)
	msgs := TickEffects(&e.EnemyEffects, &e.Monster.HP, &e.Monster.MaxHP)
	e.EffectMessages = append(e.EffectMessages, msgs...)

	// Check if DoT killed the monster
	if e.Monster.HP <= 0 {
		e.Monster.HP = 0
		e.Phase = PhaseVictory
		r = Result{Action: ActionAttack, Message: "Defeated by poison!"}
		e.Results = append(e.Results, r)
		return r
	}

	// Check for stun: if enemy is stunned, skip their turn
	if HasCondition(e.EnemyEffects, CondStun) {
		ConsumeCondition(&e.EnemyEffects, CondStun)
		r = Result{Action: ActionAttack, Message: e.Monster.Name + " is stunned!"}
		e.Results = append(e.Results, r)
		e.Phase = PhaseEnemyAct
		return r
	}

	// Boss special: alternates between fire breath and debuff attack every 3 rounds
	if e.Monster.IsBoss && e.bossAttackCounter >= 2 {
		if e.Round%6 < 3 {
			r = e.calcBossSpecial()
		} else {
			r = e.calcBossDebuff()
		}
		e.bossAttackCounter = 0
	} else {
		r = e.calcEnemyAttack()
		e.bossAttackCounter++
	}

	e.Results = append(e.Results, r)
	e.Phase = PhaseEnemyAct

	// Check if player is dead
	if e.Player.Stats.HP <= 0 {
		e.Player.Stats.HP = 0
		e.Phase = PhaseDefeat
	}

	return r
}

// AdvancePhase moves to the next logical phase after an action resolves.
// The screen calls this when it's done animating the current result.
func (e *Engine) AdvancePhase() {
	switch e.Phase {
	case PhasePlayerAct:
		if e.Monster.HP <= 0 {
			e.Phase = PhaseVictory
		} else {
			e.Phase = PhaseEnemyTurn
		}
	case PhaseEnemyAct:
		if e.Player.Stats.HP <= 0 {
			e.Phase = PhaseDefeat
		} else {
			e.PlayerDefending = false
			e.Round++
			e.Phase = PhasePlayerTurn
		}
	case PhaseFleeFaild:
		// After failed flee, enemy attacks
		e.Phase = PhaseEnemyTurn
	}
}

// --- Effective stats (base + equipment + effects) ---

// playerATK returns the player's ATK including equipment, inn buffs, and active effects.
func (e *Engine) playerATK() int {
	return e.Player.EffectiveATK() + SumStatMod(e.PlayerEffects, StatATK)
}

// playerDEF returns the player's DEF including equipment, inn buffs, and active effects.
func (e *Engine) playerDEF() int {
	return e.Player.EffectiveDEF() + SumStatMod(e.PlayerEffects, StatDEF)
}

// enemyATK returns the monster's ATK modified by active effects.
func (e *Engine) enemyATK() int {
	atk := e.Monster.ATK + SumStatMod(e.EnemyEffects, StatATK)
	if atk < 1 {
		atk = 1
	}
	return atk
}

// enemyDEF returns the monster's DEF modified by active effects.
func (e *Engine) enemyDEF() int {
	def := e.Monster.DEF + SumStatMod(e.EnemyEffects, StatDEF)
	if def < 0 {
		def = 0
	}
	return def
}

// enemySPD returns the monster's SPD modified by active effects.
func (e *Engine) enemySPD() int {
	spd := e.Monster.SPD + SumStatMod(e.EnemyEffects, StatSPD)
	if spd < 1 {
		spd = 1
	}
	return spd
}

// --- Damage calculations ---

func (e *Engine) calcPlayerAttack(multiplier float64) Result {
	atk := float64(e.playerATK()) * multiplier
	def := float64(e.enemyDEF())

	// Base damage: ATK * mult - DEF/2, with ±20% randomness
	base := atk - def/2.0
	if base < 1 {
		base = 1
	}
	variance := 0.8 + rand.Float64()*0.4 // 0.8 to 1.2
	damage := int(base * variance)
	if damage < 1 {
		damage = 1
	}

	// Critical hit: 10% chance, 1.5x damage
	crit := rand.Intn(100) < 10
	if crit {
		damage = damage * 3 / 2
	}

	e.Monster.HP -= damage
	return Result{
		Action:  ActionAttack,
		Damage:  damage,
		IsCrit:  crit,
		Message: "You attack!",
	}
}

func (e *Engine) calcPlayerMagic() Result {
	// Class-specific special moves!
	switch e.Player.Class {
	case entity.ClassKnight:
		return e.calcShieldBash()
	case entity.ClassMage:
		return e.calcFireball()
	case entity.ClassArcher:
		return e.calcSnipe()
	default:
		return e.calcGenericMagic()
	}
}

// Shield Bash (Knight): damage + stun enemy for 1 turn. Costs 3 MP.
func (e *Engine) calcShieldBash() Result {
	mpCost := 3
	if e.Player.Stats.MP < mpCost {
		return Result{Action: ActionMagic, Message: "Not enough MP!"}
	}
	e.Player.Stats.MP -= mpCost

	atk := float64(e.playerATK()) * 0.8
	def := float64(e.enemyDEF())
	base := atk - def/2.0
	if base < 1 {
		base = 1
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))
	if damage < 1 {
		damage = 1
	}

	e.Monster.HP -= damage
	AddEffect(&e.EnemyEffects, NewStatus("Stun", CondStun, 1))

	return Result{
		Action:  ActionMagic,
		Damage:  damage,
		Message: "Shield Bash!\nEnemy is stunned!",
	}
}

// Fireball (Mage): high magic damage. Costs 5 MP.
func (e *Engine) calcFireball() Result {
	mpCost := 5
	if e.Player.Stats.MP < mpCost {
		return Result{Action: ActionMagic, Message: "Not enough MP!"}
	}
	e.Player.Stats.MP -= mpCost

	atk := float64(e.playerATK()) * 2.0
	def := float64(e.enemyDEF())
	base := atk - def/4.0
	if base < 2 {
		base = 2
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))

	e.Monster.HP -= damage
	return Result{
		Action:  ActionMagic,
		Damage:  damage,
		Message: "Fireball!",
	}
}

// Snipe (Archer): guaranteed critical hit. Costs 4 MP.
func (e *Engine) calcSnipe() Result {
	mpCost := 4
	if e.Player.Stats.MP < mpCost {
		return Result{Action: ActionMagic, Message: "Not enough MP!"}
	}
	e.Player.Stats.MP -= mpCost

	atk := float64(e.playerATK())
	def := float64(e.enemyDEF())
	base := atk - def/2.0
	if base < 1 {
		base = 1
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))
	damage = damage * 2 // guaranteed double damage crit

	e.Monster.HP -= damage
	return Result{
		Action:  ActionMagic,
		Damage:  damage,
		IsCrit:  true,
		Message: "Snipe! Critical!",
	}
}

// Generic magic (fallback)
func (e *Engine) calcGenericMagic() Result {
	mpCost := 4
	if e.Player.Stats.MP < mpCost {
		return Result{Action: ActionMagic, Message: "Not enough MP!"}
	}
	e.Player.Stats.MP -= mpCost

	atk := float64(e.playerATK()) * 1.5
	def := float64(e.enemyDEF())
	base := atk - def/4.0
	if base < 1 {
		base = 1
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))
	if damage < 1 {
		damage = 1
	}

	e.Monster.HP -= damage
	return Result{Action: ActionMagic, Damage: damage, Message: "Magic blast!"}
}

func (e *Engine) calcPlayerDefend() Result {
	e.PlayerDefending = true
	return Result{
		Action:  ActionDefend,
		Message: "You brace yourself!",
	}
}

func (e *Engine) calcFlee() Result {
	if e.Monster.IsBoss {
		return Result{
			Action:  ActionDefend, // not ActionFlee — signals failure
			Message: "Can't flee a boss!",
		}
	}

	// Flee chance based on SPD ratio: base 50%, +5% per SPD advantage
	chance := 50 + (e.Player.EffectiveSPD()-e.enemySPD())*5
	if chance < 20 {
		chance = 20
	}
	if chance > 90 {
		chance = 90
	}

	if rand.Intn(100) < chance {
		return Result{
			Action:  ActionFlee,
			Message: "Got away safely!",
		}
	}

	return Result{
		Action:  ActionDefend, // signals flee failed
		Message: "Can't escape!",
	}
}

// calcUseItem resolves the player's selected item by inventory index.
// The combat screen sets SelectedItemIdx before calling PlayerAction(ActionItem).
//
// THEORY — Why the engine doesn't pick the item:
// The engine is a pure logic layer — it doesn't know about menus or cursors.
// The screen is responsible for letting the player browse their consumables
// and setting SelectedItemIdx. The engine just executes the choice. This
// keeps the separation of concerns clean: UI decides *what*, engine decides
// *how* (applying the effect, removing the item).
func (e *Engine) calcUseItem() Result {
	used := e.Player.UseItem(e.SelectedItemIdx)
	if used == nil {
		return Result{
			Action:  ActionItem,
			Healed:  0,
			Message: "No items!",
		}
	}

	msg := "Used " + used.Name + "!"
	healed := 0

	switch used.Consumable {
	case entity.ConsumeHP:
		healed = used.StatBoost
	case entity.ConsumeMP:
		msg = "Used " + used.Name + "!\nMP restored!"
	case entity.ConsumeAntidote:
		// Remove all DoT effects from the player
		cleaned := e.PlayerEffects[:0]
		for _, eff := range e.PlayerEffects {
			if eff.Type != EffDoT {
				cleaned = append(cleaned, eff)
			}
		}
		e.PlayerEffects = cleaned
		msg = "Used Antidote!\nDoTs cured!"
	case entity.ConsumeSmoke:
		// Guaranteed flee (except bosses)
		if e.Monster.IsBoss {
			msg = "Can't flee a boss!\nSmoke Bomb wasted..."
		} else {
			e.Phase = PhaseFlee
			return Result{Action: ActionFlee, Message: "Smoke Bomb!\nGot away safely!"}
		}
	case entity.ConsumeATKBuff:
		// Temporary ATK buff for 4 turns
		AddEffect(&e.PlayerEffects, NewStatMod("ATK Up", StatATK, used.StatBoost, 4))
		msg = "ATK +" + itoa(used.StatBoost) + " for 4 turns!"
	case entity.ConsumeDEFBuff:
		// Temporary DEF buff for 4 turns
		AddEffect(&e.PlayerEffects, NewStatMod("DEF Up", StatDEF, used.StatBoost, 4))
		msg = "DEF +" + itoa(used.StatBoost) + " for 4 turns!"
	}

	return Result{
		Action:  ActionItem,
		Healed:  healed,
		Message: msg,
	}
}

// calcUseSkill resolves a learned skill based on SelectedSkillIdx.
func (e *Engine) calcUseSkill() Result {
	learned := e.Player.LearnedSkills()
	if e.SelectedSkillIdx < 0 || e.SelectedSkillIdx >= len(learned) {
		return Result{Action: ActionSkill, Message: "No skill selected!"}
	}
	def := learned[e.SelectedSkillIdx]
	lvl := e.Player.SkillLevel(def.ID)
	if lvl <= 0 {
		return Result{Action: ActionSkill, Message: "Skill not learned!"}
	}

	mpCost := def.MPCost[lvl-1]
	if e.Player.Stats.MP < mpCost {
		return Result{Action: ActionSkill, Message: "Not enough MP!"}
	}
	e.Player.Stats.MP -= mpCost

	mult := def.Multiplier[lvl-1]

	// Dispatch based on skill ID for special effects
	switch def.ID {
	case entity.SkillShieldBash:
		return e.skillShieldBash(mult)
	case entity.SkillWarCry:
		return e.skillWarCry(mult)
	case entity.SkillHolyStrike:
		return e.skillHolyStrike(mult)
	case entity.SkillAegis:
		return e.skillAegis()
	case entity.SkillFireball:
		return e.skillMagicDamage("Fireball!", mult, 4.0)
	case entity.SkillIceShard:
		return e.skillIceShard(mult)
	case entity.SkillThunder:
		return e.skillThunder(mult)
	case entity.SkillMeteor:
		return e.skillMagicDamage("Meteor!", mult, 4.0)
	case entity.SkillSnipe:
		return e.skillSnipe(mult)
	case entity.SkillPoisonArrow:
		return e.skillPoisonArrow(mult)
	case entity.SkillMultiShot:
		return e.skillMultiShot(mult)
	case entity.SkillDeadeye:
		return e.skillDeadeye(mult)
	}

	return e.skillMagicDamage(def.Name+"!", mult, 2.0)
}

func (e *Engine) skillShieldBash(mult float64) Result {
	damage := e.calcDamage(mult, 2.0)
	e.Monster.HP -= damage
	AddEffect(&e.EnemyEffects, NewStatus("Stun", CondStun, 1))
	return Result{Action: ActionSkill, Damage: damage, Message: "Shield Bash!\nEnemy is stunned!"}
}

func (e *Engine) skillWarCry(mult float64) Result {
	// Buff ATK for 3 turns (effect ticks at start of turn, so 3 = lasts 2 action turns)
	buff := int(mult * 3)
	AddEffect(&e.PlayerEffects, NewStatMod("ATK Up", StatATK, buff, 3))
	return Result{Action: ActionSkill, Message: "War Cry!\nATK +" + itoa(buff) + " for 3 turns!"}
}

func (e *Engine) skillHolyStrike(mult float64) Result {
	damage := e.calcDamage(mult, 2.0)
	e.Monster.HP -= damage
	// Lifesteal: heal 50% of damage dealt
	heal := damage / 2
	if heal < 1 {
		heal = 1
	}
	e.Player.Stats.HP += heal
	if e.Player.Stats.HP > e.Player.Stats.MaxHP {
		e.Player.Stats.HP = e.Player.Stats.MaxHP
	}
	// Also grants a small Regen for 2 turns
	AddEffect(&e.PlayerEffects, NewRegen("Regen", 2+e.Player.Level/5, 2))
	return Result{Action: ActionSkill, Damage: damage, Healed: heal, Message: "Holy Strike!\nHealed " + itoa(heal) + " HP!"}
}

func (e *Engine) skillAegis() Result {
	// Aegis uses duration -1 (permanent until consumed by ConsumeCondition)
	AddEffect(&e.PlayerEffects, NewStatus("Aegis", CondAegis, -1))
	return Result{Action: ActionSkill, Message: "Aegis!\nNext hit halved!"}
}

func (e *Engine) skillMagicDamage(name string, mult, defDiv float64) Result {
	damage := e.calcMagicDamage(mult, defDiv)
	e.Monster.HP -= damage
	return Result{Action: ActionSkill, Damage: damage, Message: name}
}

func (e *Engine) skillIceShard(mult float64) Result {
	damage := e.calcMagicDamage(mult, 2.0)
	e.Monster.HP -= damage
	// Temporary SPD debuff (3 turns) instead of permanent reduction
	AddEffect(&e.EnemyEffects, NewStatMod("SPD Down", StatSPD, -3, 3))
	return Result{Action: ActionSkill, Damage: damage, Message: "Ice Shard!\nEnemy SPD -3!"}
}

func (e *Engine) skillThunder(mult float64) Result {
	// Ignores DEF entirely
	atk := float64(e.playerATK()) * mult
	damage := int(atk * (0.9 + rand.Float64()*0.2))
	if damage < 1 {
		damage = 1
	}
	e.Monster.HP -= damage
	return Result{Action: ActionSkill, Damage: damage, Message: "Thunder!\nIgnores defense!"}
}

func (e *Engine) skillSnipe(mult float64) Result {
	damage := e.calcDamage(mult, 2.0)
	damage = damage * 2 // guaranteed crit
	e.Monster.HP -= damage
	return Result{Action: ActionSkill, Damage: damage, IsCrit: true, Message: "Snipe!\nCritical hit!"}
}

func (e *Engine) skillPoisonArrow(mult float64) Result {
	damage := e.calcDamage(mult, 2.0)
	e.Monster.HP -= damage
	// Poison DoT on enemy (scales with level, 3 turns)
	poisonDmg := 3 + e.Player.Level
	AddEffect(&e.EnemyEffects, NewDoT("Poison", DoTPoison, poisonDmg, 3))
	return Result{Action: ActionSkill, Damage: damage, Message: "Poison Arrow!\nEnemy is poisoned!"}
}

func (e *Engine) skillMultiShot(mult float64) Result {
	hits := 2 + rand.Intn(2) // 2 or 3 hits
	total := 0
	for i := 0; i < hits; i++ {
		dmg := e.calcDamage(mult, 2.0)
		total += dmg
	}
	e.Monster.HP -= total
	return Result{Action: ActionSkill, Damage: total, Message: "Multi Shot!\n" + itoa(hits) + " hits!"}
}

func (e *Engine) skillDeadeye(mult float64) Result {
	damage := e.calcDamage(mult, 2.0)
	damage = damage * 3 // triple crit
	e.Monster.HP -= damage
	return Result{Action: ActionSkill, Damage: damage, IsCrit: true, Message: "Deadeye!\nTriple critical!"}
}

// calcDamage is a helper: ATK*mult - DEF/defDiv with variance.
func (e *Engine) calcDamage(mult, defDiv float64) int {
	atk := float64(e.playerATK()) * mult
	def := float64(e.enemyDEF())
	base := atk - def/defDiv
	if base < 1 {
		base = 1
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))
	if damage < 1 {
		damage = 1
	}
	return damage
}

// calcMagicDamage uses ATK*mult - DEF/defDiv (magic uses same ATK but ignores more DEF).
func (e *Engine) calcMagicDamage(mult, defDiv float64) int {
	atk := float64(e.playerATK()) * mult
	def := float64(e.enemyDEF())
	base := atk - def/defDiv
	if base < 2 {
		base = 2
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))
	if damage < 1 {
		damage = 1
	}
	return damage
}

// itoa is a tiny int-to-string helper within the combat package.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	digits := make([]byte, 0, 10)
	for n > 0 {
		digits = append(digits, byte('0'+n%10))
		n /= 10
	}
	if neg {
		digits = append(digits, '-')
	}
	// reverse
	for i, j := 0, len(digits)-1; i < j; i, j = i+1, j-1 {
		digits[i], digits[j] = digits[j], digits[i]
	}
	return string(digits)
}

func (e *Engine) calcEnemyAttack() Result {
	// Check if enemy is blinded (50% miss chance)
	if HasCondition(e.EnemyEffects, CondBlind) {
		if rand.Intn(100) < 50 {
			return Result{
				Action:         ActionAttack,
				TargetIsPlayer: true,
				Message:        e.Monster.Name + " missed!\n(Blinded)",
			}
		}
	}

	// user speed can doge atk.
	spd := e.Player.Stats.SPD // int
	// dodgedRate = spd / 2 * 1.0
	dodgedRate := spd / 2
	if dodgedRate >= 70 {
		dodgedRate = 70
	}
	if rand.Intn(100) <= dodgedRate {
		return Result{
			Action:         ActionAttack,
			TargetIsPlayer: true,
			Message:        e.Monster.Name + " missed!\n(Dodged)",
		}
	}

	// Enemy ability chance: 25% to use a special ability instead of basic attack.
	// Higher-level monsters (higher ATK) are more likely to use abilities.
	// Bosses use their own special logic (calcBossSpecial), so skip here.
	//
	// THEORY — Enemy abilities as risk/reward:
	// An enemy that just basic-attacks every turn is predictable and boring.
	// By giving enemies a chance to apply debuffs, the player has to think
	// tactically: "Do I heal this turn, or do I risk taking a poison hit?"
	// The 25% chance means abilities are surprising but not overwhelming.
	if !e.Monster.IsBoss && rand.Intn(100) < 25 {
		if r, ok := e.tryEnemyAbility(); ok {
			return r
		}
	}

	atk := float64(e.enemyATK())
	def := float64(e.playerDEF())

	if e.PlayerDefending {
		def *= 2 // defending doubles DEF
	}

	monsterCriticalDmgRate := e.Monster.CRITRATE
	critFlag := false
	if rand.Intn(100) <= monsterCriticalDmgRate {
		critFlag = true
		atk *= 2.0
	}

	base := atk - def/4.0
	if base < 1 {
		base = 1
	}
	variance := 0.8 + rand.Float64()*0.4
	damage := int(base * variance)
	if damage < 1 {
		damage = 1
	}

	// Aegis: halves damage from next hit (consumed)
	msg := e.Monster.Name + " attacks!"
	if critFlag {
		msg += " (Critical hit)"
	}
	if ConsumeCondition(&e.PlayerEffects, CondAegis) {
		damage = damage / 2
		if damage < 1 {
			damage = 1
		}
		msg = e.Monster.Name + " attacks!\nAegis absorbs half!"
	}

	e.Player.Stats.HP -= damage
	return Result{
		Action:         ActionAttack,
		Damage:         damage,
		TargetIsPlayer: true,
		Message:        msg,
	}
}

// tryEnemyAbility attempts a special enemy ability based on the monster's
// characteristics. Returns (result, true) if an ability was used.
//
// THEORY — Emergent enemy behavior from stat profiles:
// Rather than giving each monster a hardcoded ability list, we derive
// abilities from the monster's stats. High-ATK monsters do power strikes,
// high-SPD ones apply debuffs, tanky ones buff themselves. This means
// adding new monsters automatically gives them interesting combat behavior
// without writing new code for each one.
func (e *Engine) tryEnemyAbility() (Result, bool) {
	roll := rand.Intn(100)

	// Poison Bite: monsters with "Spider", "Snake", "Serpent" in name
	// or any monster with decent ATK
	if roll < 30 && e.Monster.ATK >= 8 {
		dmg := e.calcEnemyDamage(0.6)
		e.Player.Stats.HP -= dmg
		poisonDmg := 1 + e.Monster.ATK/5
		AddEffect(&e.PlayerEffects, NewDoT("Poison", DoTPoison, poisonDmg, 3))
		msg := e.Monster.Name + " bites!\nYou're poisoned!"
		return Result{Action: ActionAttack, Damage: dmg, TargetIsPlayer: true, Message: msg}, true
	}

	// Intimidate: reduces player ATK for 2 turns
	if roll < 55 && e.Monster.ATK >= 12 {
		debuff := 2 + e.Monster.ATK/6
		AddEffect(&e.PlayerEffects, NewStatMod("ATK Down", StatATK, -debuff, 3))
		msg := e.Monster.Name + " roars!\nATK -" + itoa(debuff) + "!"
		return Result{Action: ActionAttack, TargetIsPlayer: true, Message: msg}, true
	}

	// Blinding Dust: applies blind for 2 turns (misses on physical attacks)
	if roll < 70 {
		AddEffect(&e.PlayerEffects, NewStatus("Blind", CondBlind, 2))
		msg := e.Monster.Name + " throws dust!\nYou're blinded!"
		return Result{Action: ActionAttack, TargetIsPlayer: true, Message: msg}, true
	}

	// Self-buff: DEF Up for 3 turns (tougher enemies protect themselves)
	if roll < 85 && e.Monster.DEF >= 8 {
		buff := 2 + e.Monster.DEF/4
		AddEffect(&e.EnemyEffects, NewStatMod("DEF Up", StatDEF, buff, 3))
		msg := e.Monster.Name + " hardens!\nDEF +" + itoa(buff) + "!"
		return Result{Action: ActionAttack, TargetIsPlayer: true, Message: msg}, true
	}

	return Result{}, false
}

// calcEnemyDamage is a helper for enemy abilities that deal reduced damage.
func (e *Engine) calcEnemyDamage(mult float64) int {
	atk := float64(e.enemyATK()) * mult
	def := float64(e.playerDEF())
	if e.PlayerDefending {
		def *= 2
	}
	base := atk - def/2.0
	if base < 1 {
		base = 1
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))
	if damage < 1 {
		damage = 1
	}

	// Aegis check
	if ConsumeCondition(&e.PlayerEffects, CondAegis) {
		damage = damage / 2
		if damage < 1 {
			damage = 1
		}
	}
	return damage
}

func (e *Engine) calcBossSpecial() Result {
	// Fire breath: high damage, ignores half defense
	atk := float64(e.enemyATK()) * 1.8
	def := float64(e.playerDEF())

	if e.PlayerDefending {
		def *= 2
	}

	base := atk - def/4.0
	if base < 2 {
		base = 2
	}
	variance := 0.9 + rand.Float64()*0.2
	damage := int(base * variance)

	// Boss fire breath also applies Burn DoT (2 damage for 3 turns)
	msg := e.Monster.Name + " breathes fire!"
	AddEffect(&e.PlayerEffects, NewDoT("Burn", DoTBurn, 2+e.Monster.ATK/5, 3))
	msg += "\nYou're burning!"

	// Aegis still blocks half
	if ConsumeCondition(&e.PlayerEffects, CondAegis) {
		damage = damage / 2
		if damage < 1 {
			damage = 1
		}
		msg += "\nAegis absorbs half!"
	}

	e.Player.Stats.HP -= damage
	return Result{
		Action:         ActionMagic,
		Damage:         damage,
		TargetIsPlayer: true,
		Message:        msg,
	}
}

// calcBossDebuff is the boss's secondary special: a debuff-focused attack.
// Alternates with fire breath to create tactical variety.
//
// THEORY — Boss phase rotation:
// Classic RPGs give bosses a rotation of abilities: FF bosses alternate between
// physical attacks, magic, and debuffs. This creates a rhythm the player can
// learn and adapt to: "Fire breath is coming, I should Defend or use Aegis."
// Our boss alternates: attack → attack → fire breath → attack → attack → debuff.
// The debuff special applies ATK Down + DEF Down, forcing the player to choose:
// do they cleanse/wait it out, or push through with reduced stats?
func (e *Engine) calcBossDebuff() Result {
	// Terrifying Roar: moderate damage + ATK Down + SPD Down
	atk := float64(e.enemyATK()) * 1.2
	def := float64(e.playerDEF())
	if e.PlayerDefending {
		def *= 2
	}
	base := atk - def/3.0
	if base < 1 {
		base = 1
	}
	damage := int(base * (0.9 + rand.Float64()*0.2))

	// Aegis check
	msg := e.Monster.Name + " roars!"
	if ConsumeCondition(&e.PlayerEffects, CondAegis) {
		damage = damage / 2
		if damage < 1 {
			damage = 1
		}
		msg += "\nAegis absorbs half!"
	}

	// Apply debuffs
	atkDebuff := 3 + e.Monster.ATK/8
	AddEffect(&e.PlayerEffects, NewStatMod("ATK Down", StatATK, -atkDebuff, 3))
	AddEffect(&e.PlayerEffects, NewStatMod("SPD Down", StatSPD, -2, 3))
	msg += "\nATK & SPD down!"

	e.Player.Stats.HP -= damage
	return Result{
		Action:         ActionMagic,
		Damage:         damage,
		TargetIsPlayer: true,
		Message:        msg,
	}
}
